### ISSUE TITLE
Investigate NPM package hosting options and their API/integrations for possible usage

### ISSUE THREAD

**Issue by Jeffrey-Campbell-Zapdot** [jeffcampbellmakesgames/unity-package-tools#4]
Right now the only native Unity way of supporting package dependencies that are NOT from Unity (text mesh pro, timeline, etc...) is by way of registries that would offer the user a way to select which package hosting server their packages can be from. It would be nice if there were options in package tools to allow for integrating with one or more of these NPM hosting services. Research and investigation should be done to see which if any of these would be likely contenders via either a CLI or REST interface.

**Comment by jeffcampbellmakesgames** [comment]
I am satisfied with using OpenUPM as a native package manager since no additional code functionality needs to be written to support it and it can dual leverage the package export option this library supports. See [here](https://github.com/jeffcampbellmakesgames/unity-package-tools/issues/7) for more info.
